# Generated by Django 5.1.3 on 2024-11-27 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GuardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'Día'), ('night', 'Noche'), ('weekend', 'Fin de semana')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_assignments', to='routes.route')),
            ],
            options={
                'unique_together': {('route', 'guard', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('checkpoint_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='routes.route')),
            ],
            options={
                'ordering': ['checkpoint_order'],
            },
        ),
        migrations.CreateModel(
            name='RouteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_runs', to='routes.guardassignment')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='routes.checkpoint')),
                ('route_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_scans', to='routes.routerun')),
            ],
            options={
                'unique_together': {('checkpoint', 'route_run')},
            },
        ),
    ]
