# Generated by Django 5.1.3 on 2024-11-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guardassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='guardassignment',
            name='guard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='guardassignment',
            name='date',
        ),
    ]
