# Generated by Django 5.1.3 on 2024-11-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_guardassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='checkpoint',
            old_name='checkpoint_order',
            new_name='order',
        ),
    ]
