# Generated by Django 5.1.3 on 2025-01-20 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_type', models.CharField(choices=[('person', 'Person'), ('car', 'Car')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('motive', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('remission_guide', models.CharField(blank=True, max_length=100, null=True)),
                ('bill', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_plate', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['route', 'order'], name='routes_chec_route_i_7c6b95_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['qr_code'], name='routes_chec_qr_code_2356d2_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpointscan',
            index=models.Index(fields=['route_run', 'scanned_at'], name='routes_chec_route_r_44819f_idx'),
        ),
        migrations.AddIndex(
            model_name='guardassignment',
            index=models.Index(fields=['guard'], name='routes_guar_guard_i_9582bc_idx'),
        ),
        migrations.AddIndex(
            model_name='guardassignment',
            index=models.Index(fields=['route'], name='routes_guar_route_i_63dd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['guard', 'timestamp'], name='routes_inci_guard_i_b9144f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['route_run'], name='routes_inci_route_r_2e3cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='routerun',
            index=models.Index(fields=['assignment', 'completed'], name='routes_rout_assignm_14ea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='routerun',
            index=models.Index(fields=['start_time'], name='routes_rout_start_t_7d03b1_idx'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='route_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='routes.routerun'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['route_run', 'occurrence_type'], name='routes_occu_route_r_e79d63_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['timestamp'], name='routes_occu_timesta_16dab5_idx'),
        ),
    ]
