# Generated by Django 5.1.3 on 2025-01-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_populate_client_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
