# Generated by Django 5.1.3 on 2025-01-27 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def forward_func(apps, schema_editor):
    Client = apps.get_model("routes", "Client")
    User = apps.get_model("auth", "User")
    for client in Client.objects.filter(user__isnull=True):
        username = f"client_{client.id}"
        user = User.objects.create(
            username=username,
            password=make_password("changeme")  # You might want to generate a random password here
        )
        client.user = user
        client.save()

def reverse_func(apps, schema_editor):
    pass  # We don't want to delete users if we revert this migration

class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_populate_client_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]

